version: "3"
services:
  caddy:
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./prod/configs/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./prod/data/caddy:/data:rw

  analysis:
    volumes:
        - ./prod/configs/storage:/conf/storage/

  mongodb:
    ports:
      - 27017:27017
    volumes:
      - ./dev/data/mongodb:/data/db
