version: "3"
services:
  caddy:
    image: caddy:2.1.1
    restart: always
    networks:
      - e-mission

  e-mission:
    image: emission/e-mission-server:2.8.0
    restart: always
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
      - WEB_SERVER_HOST=0.0.0.0
    networks:
      - e-mission

  analysis:
    build: dockerfiles/analysis
    restart: always
    depends_on:
      - e-mission
      - mongodb
    environment:
      # TODO: pass DB_HOST down to db.conf
      - DB_HOST=mongodb
      - WEB_SERVER_HOST=0.0.0.0
    networks:
      - e-mission

  mongodb:
    image: mongo:3.4
    restart: always
    networks:
      - e-mission

networks:
  e-mission:
